### ISSUE TITLE
Provide a shaded jar to avoid dependencies issues

### ISSUE THREAD

**Issue by sbailliez** [DataDog/datadog-api-client-java#1179]
@therve  I'm opening this again as a follow up to #893  as this has been incorrectly resolved as a standalone jar without shading, so the problem remains as it does not solve compatibility issues between implementation specific libs used by datadog that  could conflict with a project one.

**Is your feature request related to a problem? Please describe.**

Datadog api client depends on popular third-party libraries that are fast moving and which implementation may conflict with the one of the application it needs to be integrated with. Clashes are often exacerbated by excessive transitive dependencies issues.

**Describe the solution you'd like**

Provide a shaded/standalone jar that is self contained with no dependencies (except for the api interfaces needed)

Examples:
- glassfish jersey  is repackaging asm and guava
- uber jvm profile is relocating all dependencies. https://github.com/uber-common/jvm-profiler/blob/master/pom.xml
- aws sdk is relocating dependencies. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-bundle/pom.xml
See reasoning https://aws.amazon.com/blogs/developer/java-sdk-bundle/

**Describe alternatives you've considered**

- Add a lengthy list of exclusions to the datadog-api-client and hope for the best that the glassfish client and jackson code in use will be compatible with the one used in the application

- Fork the datadog-api-client code and maintain it to be compatible

None of those solution are adequate for increased adoption of the datadog-api-client library across a wide range of applications and benefit from any improvement of the project in a safe way.

**Comment by therve** [comment]
Thanks for your report, sorry I misunderstood the original request. We'll look into it.

**Comment by sbailliez** [comment]
Thank you @therve !

**Comment by sbailliez** [comment]
Any possibility to get this prioritized? We are staying away from this client for now because of the dependencies.

**Comment by therve** [comment]
We started looking into it at #1243 , should be in the next releese.

**Comment by therve** [comment]
Released 1.6.0 with the new jar, let us know if that works for you. Thanks.
