### ISSUE TITLE
Common interface/implementation of HttpClient for all APIs

### ISSUE THREAD

**Issue by abrooksv** [DataDog/datadog-api-client-java#1235]
**Is your feature request related to a problem? Please describe.**
Right now each API version namespace takes a different ApiClient (`com.datadog.api.v1.client.ApiClient` vs `com.datadog.api.v2.client.ApiClient`)
If you need to use APIs from both V1 and V2, you have to configure each ApiClient separately leading to duplicated code for things such as:
* Timeouts
  * Technically you can pass in the Jersey client pre-configured, but then those timeouts differ form Jersey vs the ApiClient getters.
  * I am not sure why ApiClient stores timeouts as an instance variable as well as configures Jersey: https://github.com/DataDog/datadog-api-client-java/blob/master/src/main/java/com/datadog/api/v1/client/ApiClient.java#L825-L845
* API Keys
* User Agent

**Describe the solution you'd like**
I would like to see ApiClient exist outside of the versioned namespace and able to be used across multiple versions, 

**Describe alternatives you've considered**
A common interface across all the API Clients would also work that defines the common setters though this may have higher memory footprint due to duplicate API Clients

**Comment by therve** [comment]
Thanks for the report. That's definitely on the roadmap (though we'll need to break compatibility most likely). We're constrained by openapi-generator today, but we're slowly migrating away, and once it's done it'll be easy to achieve something like what you need.

**Comment by abrooksv** [comment]
I think with the move to `com.datadog.api.client` we can call this done now 😄 Thx!
