### ISSUE TITLE
java.lang.ClassNotFoundException: jakarta.ws.rs.client.InvocationCallback

### ISSUE THREAD

**Issue by VazkenA98** [DataDog/datadog-api-client-java#1684]
Spring boot version: 2.6.4
Java version: 11
datadog-api-client: 2.9.0

ApiClient defaultClient = ApiClient.getDefaultApiClient();
`java.lang.ClassNotFoundException: jakarta.ws.rs.client.InvocationCallback
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]`

**Comment by therve** [comment]
Can you try the shaded jar? Thanks.

**Comment by VazkenA98** [comment]
Implemented the following plugin, and still same issue.

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.2.1</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <transformers>
                            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                <mainClass>com.example.MyApplication</mainClass>
                            </transformer>
                        </transformers>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>

**Comment by therve** [comment]
Hi, I don't think it does what I meant. I meant using the shaded artifact of the datadog API client. Can you share the dependency section of the client?

**Comment by therve** [comment]
Closing for now, let me know if the shaded jar worked for you. Thanks.

**Comment by harry-blackbird** [comment]
i'm getting the same issue with the shaded jar: 
```
    implementation("com.datadoghq:datadog-api-client:2.10.0:shaded-jar")
```
