### ISSUE TITLE
Artifact id is not present in central maven repository

### ISSUE THREAD

**Issue by ankumar-apptio** [DataDog/datadog-api-client-java#254]
<artifactId>datadog-api-client</artifactId>

Could not import the jars using this aritfact id. Please look into this.

**Comment by bkabrda** [comment]
Hey, this repository has been opensourced quite recently and we're still working towards the first official release. I'll update this issue once we have it uploaded to Maven Central.

**Comment by gzussa** [comment]
Hi @ankumar-apptio, We released `1.0.0.beta.2`. See https://mvnrepository.com/artifact/com.datadoghq/datadog-api-client. Note that it will stay beta for quite some time and until it matures a little. It means that upcoming new versions most probably won't be backward compatible. Make sure to pin the version in your production environment. Using `latest` version is not recommended as a best practice
