### ISSUE TITLE
Don't require passing concrete HashMap type

### ISSUE THREAD

**Issue by rehevkor5** [DataDog/datadog-api-client-java#513]
**Describe the bug**

ApiClient#configureApiKeys should accept a `Map` instead of requiring `HashMap`.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - Version: 1.0.0-beta.7

**Comment by rehevkor5** [comment]
I cannot follow the instruction "Add severity/ label." as the labels are not editable.

**Comment by nmuesch** [comment]
Hey @rehevkor5 thanks for the issue report. I've opened a PR upstream to the client generator to switch to allowing this method to accept the Map interface. https://github.com/OpenAPITools/openapi-generator/pull/7982

**Comment by nmuesch** [comment]
@rehevkor5 In the meantime, I've updated the client directly to no longer require the concrete Map type https://github.com/DataDog/datadog-api-client-java/pull/540
I'll go ahead and close this issue out, but let us know if you experience any further issues here.
