### ISSUE TITLE
Version 1.0.0 is not available in Mavne Central

### ISSUE THREAD

**Issue by Shpota** [DataDog/datadog-api-client-java#757]
**Describe the bug**
It is not possible to fetch the 1.0.0 version of the library from Maven Central.

**To Reproduce**
1. Create an empty Gradle project
2. Add the dependency to `"com.datadoghq:datadog-api-client:1.0.0"` like it is suggested [in the documentation](https://docs.datadoghq.com/api/latest/?code-lang=java)
3. Try to build the project
4. See that Gradle cannot get the dependency from Maven Central

**Expected behavior**
It should be possible to get the library from a central repository. 

**Additional context**
Apparently the library is absent in[ maven central](https://repo.maven.apache.org/maven2/com/datadoghq/datadog-api-client/), only beta versions are available. It is either deployed in some other place (checked jcenter, not available either), or the documentation should suggest to use beta versions.

**Comment by nmuesch** [comment]
Hey @Shpota Thanks for the issue report. We just started releasing beta 10 of 1.0.0 today (should be synced to maven shortly). 

Thanks for sharing the docs link, you're right that the latest available release is 1.0.0-beta.9. I'll work on getting the documentation updated to reflect this. In the meantime, you can use beta9 from the central repository here - https://mvnrepository.com/artifact/com.datadoghq/datadog-api-client/1.0.0-beta.9

**Comment by Shpota** [comment]
@nmuesch I tried the latest beta that was available as of yesterday (probably 8), but the code from the documentation would not compile against it.

**Comment by nmuesch** [comment]
There were a number of changes that went out with the last release, beta10, and should include support for the code from the documentation. I believe this release is still being synced, but from a quick test it looks like it can be pulled. Can you try using: `com.datadoghq:datadog-api-client:1.0.0-beta10` 

Note, no `.` between `beta` and `10`. This was something that was fixed between beta.9 and beta10 as well. 

If you still experience compilation issues, can you share the specific endpoints and any code examples so I can take a deeper look? Thanks!

**Comment by nmuesch** [comment]
Hey @Shpota The readme and documentation should be fully updated now to reflect the beta10 release. I'll go ahead and close this issue but let us know if you continue to hit any issues here!
