### ISSUE TITLE
Response body of ApiException is null when receiving a 400 error while trying to create events

### ISSUE THREAD

**Issue by pdwood** [DataDog/datadog-api-client-java#879]
**Describe the bug**

While trying to debug an application I am working on that uses the DataDog API to create events, I received a 400 Bad Request error whose `responseBody` was `null`. This made it difficult to troubleshoot the HTTP error, because there was no easy way to access an explanation of why the request was invalid. 

**To Reproduce**

```java
  dataDogClient = Configuration.getDefaultApiClient();
  dataDogClient.setApiKey(API_KEY);
  eventsApi = new EventsApi(dataDogClient);
  EventCreateRequest request = new EventCreateRequest();
  request.setTitle("Request Title");
  // Date.getTime() returns a timestamp in milliseconds, but the API expects a timestamp in seconds.
  request.setDateHappened(Date.now().getTime());
  try {
    eventsApi.createEvent(request);
  } catch(ApiException e) {
    // This prints "null" instead of an explanation of why the request failed
    System.out.println(e.getResponseBody());
  }
```
**Expected behavior**

I expect `e.getResponseBody()` to return an object containing the string `"Event too far in the future"`, which is the error message that the API returns. Instead, the response body is null.

**Environment and Versions (please complete the following information):**

On Windows 10, a Maven project with the following dependency:
```xml
        <dependency>
            <groupId>com.datadoghq</groupId>
            <artifactId>datadog-api-client</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by therve** [comment]
Hi,

Can you provide a full running example? I tried the following one and it failed as expected: 

```
import java.util.Date;
import com.datadog.api.v1.client.ApiClient;
import com.datadog.api.v1.client.ApiException;
import com.datadog.api.v1.client.Configuration;
import com.datadog.api.v1.client.model.*;
import com.datadog.api.v1.client.api.EventsApi;

public class Example {
    public static void main(String[] args) {
        ApiClient defaultClient = Configuration.getDefaultApiClient();

        EventsApi apiInstance = new EventsApi(defaultClient);
        EventCreateRequest body = new EventCreateRequest(); // EventCreateRequest | Event request object
        body.setTitle("Request Title");
        body.setDateHappened(new Date().getTime());
        try {
            EventCreateResponse result = apiInstance.createEvent(body);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling EventsApi#createEvent");
            System.err.println("Status code: " + e.getCode());
            System.err.println("Reason: " + e.getResponseBody());
            System.err.println("Response headers: " + e.getResponseHeaders());
            e.printStackTrace();
        }
    }
}
```.

Thanks.

**Comment by pdwood** [comment]
I can confirm that the example you gave does work. When comparing your example to my project (which is a Spring-based web application) in a debugger, it seems that the classes being used for the HTTP request are different; the example uses a JerseyClient whereas my project uses a ResteasyClient. Somehow, the response returned by the ResteasyClient returns false for `hasEntity()`. I will investigate further.

**Comment by lav-kush** [comment]
How do we configure endpoint of victoriametrics in Datadog agent submit metrics api in java?
Any reference would be appreciated.

**Comment by therve** [comment]
Closing this one for now. Hopefully with the shaded jar there is now an option for it not to happen. Feel free to reopen if that's still an issue, thanks.
