### ISSUE TITLE
Provide a shaded/standalone jar to avoid dependencies issues

### ISSUE THREAD

**Issue by sbailliez** [DataDog/datadog-api-client-java#893]
**Is your feature request related to a problem? Please describe.**

Datadog api client depends on popular third-party libraries that are fast moving and which implementation may conflict with the one of the application it needs to be integrated with. Clashes are often exacerbated by excessive transitive dependencies issues.

**Describe the solution you'd like**

Provide a shaded/standalone jar that is self contained with no dependencies (except for the api interfaces needed)

Examples:
- glassfish jersey  is repackaging asm and guava
- uber jvm profile is relocating all dependencies. https://github.com/uber-common/jvm-profiler/blob/master/pom.xml
- aws sdk is relocating dependencies. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-bundle/pom.xml
See reasoning https://aws.amazon.com/blogs/developer/java-sdk-bundle/

**Describe alternatives you've considered**

- Add a lengthy list of exclusions to the datadog-api-client and hope for the best that the glassfish client and jackson code in use will be compatible with the one used in the application

- Fork the datadog-api-client code and maintain it to be compatible

None of those solution are adequate for increased adoption of the datadog-api-client library across a wide range of applications and benefit from any improvement of the project in a safe way.

**Comment by baileyatwork** [comment]
This issue is still reproducible. We're still waiting for a shaded JAR to be provided by Datadog.

**Comment by Nabeelperson** [comment]
This is still an issue. I am able to reproduce it as well.

**Comment by BobbyJohansen** [comment]
@therve Thank you for making an Uber Jar, is it possible to also shade the jar? We are running into conflicts with the jackson dependency being at the root namespace.
